name: Update Web Assets (Minimal with Archive Option)

on:
  workflow_dispatch:
    inputs:
      link1:
        description: "Nowy URL dla przycisku next-description"
        required: false
      link2:
        description: "Nowy URL dla przycisku next-but"
        required: false
      image1_url:
        description: "URL nowego obrazka (banner_next.png)"
        required: false
      archive_current_banner:
        description: "Zarchiwizuj obecne zdjęcie wydarzenia jako kolejny numer"
        required: false
        default: "false"
        type: boolean

permissions:
  contents: write

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Archive current banner if checkbox is selected
        if: ${{ github.event.inputs.archive_current_banner == 'true' }}
        run: |
          mkdir -p images/archive
          num=$(ls images/archive | grep -E '^[0-9]+\.png$' | sed 's/\.png//' | sort -n | tail -n 1)
          if [ -z "$num" ]; then
            next=1
          else
            next=$((num + 1))
          fi
          cp images/banner_next.png images/archive/${next}.png
          echo "Skopiowano jako: images/archive/${next}.png"

      - name: Download new image (banner_next.png)
        if: ${{ github.event.inputs.image1_url != '' }}
        run: |
          curl -L "${{ github.event.inputs.image1_url }}" -o images/banner_next.png

      - name: Update links in HTML (using awk)
        run: |
          cp index.html index_tmp.html

          if [ "${{ github.event.inputs.link1 }}" != "" ]; then
            awk 'BEGIN{RS="</a>"; ORS="</a>\n"} /class="[^"]*meeting-btn[^"]*meeting-btn-next-description[^"]*"/ {sub(/href="[^"]*"/, "href=\"${{ github.event.inputs.link1 }}\"")} {print}' index_tmp.html > index.html
            cp index.html index_tmp.html
          fi

          if [ "${{ github.event.inputs.link2 }}" != "" ]; then
            awk 'BEGIN{RS="</a>"; ORS="</a>\n"} /class="[^"]*meeting-btn[^"]*meeting-btn-next-but[^"]*"/ {sub(/href="[^"]*"/, "href=\"${{ github.event.inputs.link2 }}\"")} {print}' index_tmp.html > index.html
          fi

          rm -f index_tmp.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html images/banner_next.png images/archive || true
          git diff --cached --quiet || (git commit -m "Aktualizacja strony (linki, obrazek i/lub archiwizacja)" && git push)
