name: Update Web Assets with Backup (Flexible)

on:
  workflow_dispatch:
    inputs:
      link1:
        description: "Nowy URL dla przycisku next-description"
        required: false
      link2:
        description: "Nowy URL dla przycisku next-but"
        required: false
      link3:
        description: "Nowy URL dla przycisku prev"
        required: false
      image1_url:
        description: "URL nowego obrazka (banner_next.png)"
        required: false
      image2_url:
        description: "URL nowego obrazka (banner_previous.png)"
        required: false

permissions:
  contents: write

jobs:
  update-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Backup current images (if needed)
        if: ${{ github.event.inputs.image1_url != '' || github.event.inputs.image2_url != '' }}
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          mkdir -p images/history

          if [ -f images/banner_next.png ] && [ "${{ github.event.inputs.image1_url }}" != "" ]; then
            cp images/banner_next.png images/history/banner_next_$TIMESTAMP.png
          fi

          if [ -f images/banner_previous.png ] && [ "${{ github.event.inputs.image2_url }}" != "" ]; then
            cp images/banner_previous.png images/history/banner_previous_$TIMESTAMP.png
          fi

      - name: Download new image1 (banner_next.png)
        if: ${{ github.event.inputs.image1_url != '' }}
        run: |
          curl -L "${{ github.event.inputs.image1_url }}" -o images/banner_next.png

      - name: Download new image2 (banner_previous.png)
        if: ${{ github.event.inputs.image2_url != '' }}
        run: |
          curl -L "${{ github.event.inputs.image2_url }}" -o images/banner_previous.png

      - name: Update links in HTML
        run: |
          if [ "${{ github.event.inputs.link1 }}" != "" ]; then
            sed -i '/class="[^"]*meeting-btn[^"]*meeting-btn-next-description[^"]*"/ s|href="[^"]*"|href="${{ github.event.inputs.link1 }}"|' index.html
          fi
          if [ "${{ github.event.inputs.link2 }}" != "" ]; then
            sed -i '/class="[^"]*meeting-btn[^"]*meeting-btn-next-but[^"]*"/ s|href="[^"]*"|href="${{ github.event.inputs.link2 }}"|' index.html
          fi
          if [ "${{ github.event.inputs.link3 }}" != "" ]; then
            sed -i '/class="[^"]*meeting-btn[^"]*meeting-btn-prev[^"]*"/ s|href="[^"]*"|href="${{ github.event.inputs.link3 }}"|' index.html
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html images/banner_*.png images/history || true
          git diff --cached --quiet || (git commit -m "Aktualizacja strony (wybrane zmiany)" && git push)
